### PR TITLE
improv: added timer support for CAN packets, which

### PR DESCRIPTION
**Pull request by yashkmittal**
allows for rate-limiting, reducing clog on bus

* Added two hashmaps that store the period and curr_time of each ID

* Functions related to timers are similar to mailbox functions

fix: can_send supports data lengths from 1 - 8 bytes

### CODE REVIEW

**Comment by yashkmittal** [comment]
One question:

* Since we want to force the use of periods for CAN, should we just combine can_send_periodic() code with can_send(), rather than having a separate function?

**Review by matt-mekha — CHANGES_REQUESTED** [review]
see slack

**Comment by yashkmittal** [comment]
Changes made:

* Naming Scheme now will use TxBox and RxBox rather than Timer and Mailbox. It better tells what the eventual role of these buffers will be (whether to deal with transmitting or receiving)
* Sending can packets now requires a initialization of the ID as a TxBox to force users to set a max tx rate (although they could set their period to 0 sec lol)
* Static functions are moved to cpp file rather than h file. We do not want users to think they can call these functions (since they show up in the tooltip suggestions in Clion IDE if we put in .h file)
* Example of this being used is this branch: https://github.com/LonghornRacingElectric/vcu-firmware-2024/tree/periodic-example.
It is shown for hvc, inverter, and pdu, where each function has an update function that sends out RxBoxes and handles TxBoxes (after calling can_processRxFIFO)

**Comment by yashkmittal** [comment]
I was not able to implement the send CAN functionality that you wanted, where main sends out ALL can messages. This is because there are just too many IDs that I need to handle. I would have to implement separate CAN TxBoxes structs for each ID, which would need to be hashed and vectorized (so that there is a quick key-value pair with ID to box and we could access all transmissions at once to be pushed to FIFO), which requires them to be a class and have functions, and so on with all the fun C++ stuff. 

I think it would be best for each Driver to send the CAN messages rather all at once by main. Each loop runs will run within 1-2 ms, so the timing wouldn't be much off if use start loop time as the reference for delta time, esp with 10 - 250 ms periods.

**Pull request merged**
